### ISSUE TITLE
AttributeError: '_io.TextIOWrapper' object has no attribute 'compile'

### ISSUE THREAD

**Issue by ollieglass** [jmcarp/sqlalchemy-postgres-copy#4]
I get this error trying to load a CSV file into Postgres

**Comment by jmcarp** [comment]
Could you attach a code snippet I can use to reproduce the error?

**Comment by ollieglass** [comment]
Sorry, I changed approach and don't have the code to hand any more.

**Comment by jmcarp** [comment]
Got it, feel free to reopen if you run into the issue again.
